<p:declare-step
	xmlns:p="http://www.w3.org/ns/xproc"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:dxar="https://www.daliboris.cz/ns/xproc/archive"
	xmlns:c="http://www.w3.org/ns/xproc-step"
	xmlns:xhtml="http://www.w3.org/1999/xhtml"
	xmlns:dxt="https://www.daliboris.cz/ns/xproc/test"
	name="test-suite"
	version="3.0">

	<p:import href="../../xproc/archive-xpc-lib.xpl" />
 <p:option name="serialization" select="map {'indent' : true()}" static="true" />

	<p:documentation>
		<xhtml:section>
			<xhtml:h2>Test suite for archive-xpc-lib</xhtml:h2>
			<xhtml:p>Runs each scenario against the fixture in <xhtml:code>../input/root</xhtml:code>,
				reads back every created ZIP with <xhtml:code>p:archive-manifest</xhtml:code> and compares
				the archive names and entry names with the expected ones and with the manifests
				returned on the <xhtml:code>manifest</xhtml:code> port of the library steps.
				The report is returned on the <xhtml:code>result</xhtml:code> port and stored
				to <xhtml:code>../output/test-results.xml</xhtml:code>; if any test fails, the pipeline ends with an error.</xhtml:p>
		</xhtml:section>
	</p:documentation>

 <p:output port="result" primary="true" pipe="result@store-report" serialization="$serialization" />

	<p:option name="input-directory" select="'../input/root'" as="xs:string" />
	<p:option name="output-directory" select="'../output'" as="xs:string" />
	<p:option name="fail-on-error" select="true()" as="xs:boolean" />

	<!--
		Compares ZIP archives (given by the c:result documents from the result-uri port)
		with the expected content: a map from archive file name to the expected entry names.
		Also compares the manifests generated by the library (manifest port) with the manifests
		read back from the ZIP files by p:archive-manifest; both sequences are paired by position.
	-->
	<p:declare-step type="dxt:check-archives" name="check">
		<p:input port="source" primary="true" sequence="true" />
		<p:input port="manifest" sequence="true" />
		<p:output port="result" primary="true" />
	 <p:output port="check" primary="false" pipe="result@manifest-check" />
		
		<p:option name="test-name" as="xs:string" required="true" />
		<p:option name="description" as="xs:string" select="''" />
		<p:option name="expected" as="map(xs:string, xs:string*)" required="true" />
		
		<p:for-each>
			<p:with-input pipe="source@check" />
			<p:variable name="uri" select="string(/*)" />
			<p:load href="{$uri}" content-type="application/zip" />
			<p:archive-manifest />
			<p:add-attribute attribute-name="file-name" attribute-value="{tokenize($uri, '/')[last()]}" />
		</p:for-each>
		<p:wrap-sequence wrapper="dxt:archives" name="archives" />
		
		<p:wrap-sequence wrapper="dxt:generated-manifests" name="generated-manifests">
			<p:with-input pipe="manifest@check" />
		</p:wrap-sequence>
		
		<p:wrap-sequence wrapper="dxt:check">
			<p:with-input pipe="result@archives result@generated-manifests" />
		</p:wrap-sequence>
		
		<p:identity name="manifest-check" />
	
		<p:xslt>
			<p:with-input port="stylesheet" href="../xslt/check-archives.xsl" />
			<p:with-option name="parameters" select="map{'test-name' : $test-name, 'description' : $description, 'expected' : $expected}" />
		</p:xslt>
	</p:declare-step>

	<p:variable name="base-uri" select="static-base-uri()" />

	<!-- 1: filter given as a plain string in an attribute (backward compatibility), max-depth 1 -->
	<dxar:archive-directory name="single-filter-depth-1"
		input-directory="{$input-directory}"
		output-directory="{$output-directory}/single-filter-depth-1"
		output-file-name-pattern="single-filter-depth-1.zip"
		filter=".*\.xml"
		base-uri="{$base-uri}" />
	<dxt:check-archives name="single-filter-depth-1-check" test-name="single-filter-depth-1" description="Single filter as a string attribute, max-depth 1: only files of the top-level directory.">
		<p:with-input pipe="result-uri@single-filter-depth-1" />
		<p:with-input port="manifest" pipe="manifest@single-filter-depth-1" />
		<p:with-option name="expected" select="map{
			'single-filter-depth-1.zip' : ('root.file-1.xml')
			}" />
	</dxt:check-archives>
	<p:identity name="t01" />
 <p:store href="{$output-directory}/single-filter-depth-1/check.xml" serialization="$serialization">
		<p:with-input pipe="check@single-filter-depth-1-check" />
	</p:store>

	<!-- 2: single filter, max-depth 3 -->
	<dxar:archive-directory name="single-filter-depth-3"
		input-directory="{$input-directory}"
		output-directory="{$output-directory}/single-filter-depth-3"
		output-file-name-pattern="single-filter-depth-3.zip"
		max-depth="3"
		base-uri="{$base-uri}">
		<p:with-option name="filter" select="'.*\.xml'" />
	</dxar:archive-directory>
	<dxt:check-archives name="single-filter-depth-3-check" test-name="single-filter-depth-3" description="Single filter, max-depth 3: XML files from all levels, subdirectory paths kept.">
		<p:with-input pipe="result-uri@single-filter-depth-3" />
		<p:with-input port="manifest" pipe="manifest@single-filter-depth-3" />
		<p:with-option name="expected" select="map{
			'single-filter-depth-3.zip' : (
				'root.file-1.xml',
				'level-1-1/level-1-1.file-1.xml',
				'level-1-1/level-1-1.file-2.xml',
				'level-1-1/level-2-1/level-2-1.file-1.xml',
				'level-1-1/level-2-1/level-2-1.file-2.xml',
				'level-1-2/level-1-2.file-1.xml',
				'level-1-2/level-1-2.file-2.xml')
			}" />
	</dxt:check-archives>
	<p:identity name="t02" />
 <p:store href="{$output-directory}/single-filter-depth-3/check.xml" serialization="$serialization">
		<p:with-input pipe="check@single-filter-depth-3-check" />
	</p:store>

	<!-- 3: two filters -->
	<dxar:archive-directory name="multiple-filters"
		input-directory="{$input-directory}"
		output-directory="{$output-directory}/multiple-filters"
		output-file-name-pattern="multiple-filters.zip"
		max-depth="3"
		base-uri="{$base-uri}">
		<p:with-option name="filter" select="('.*\.xml', '.*\.txt')" />
	</dxar:archive-directory>
	<dxt:check-archives name="multiple-filters-check" test-name="multiple-filters" description="Two filters (XML, TXT): files matching any of them, JSON excluded.">
		<p:with-input pipe="result-uri@multiple-filters" />
		<p:with-input port="manifest" pipe="manifest@multiple-filters" />
		<p:with-option name="expected" select="map{
			'multiple-filters.zip' : (
				'root.file-1.xml',
				'root.notes.txt',
				'level-1-1/level-1-1.file-1.xml',
				'level-1-1/level-1-1.file-2.xml',
				'level-1-1/level-2-1/level-2-1.file-1.xml',
				'level-1-1/level-2-1/level-2-1.file-2.xml',
				'level-1-1/level-2-1/level-2-1.notes.txt',
				'level-1-2/level-1-2.file-1.xml',
				'level-1-2/level-1-2.file-2.xml')
			}" />
	</dxt:check-archives>
	<p:identity name="t03" />
 <p:store href="{$output-directory}/multiple-filters/check.xml" serialization="$serialization">
		<p:with-input pipe="check@multiple-filters-check" />
	</p:store>

	<!-- 4: empty sequence = no filtering -->
	<dxar:archive-directory name="empty-filter"
		input-directory="{$input-directory}"
		output-directory="{$output-directory}/empty-filter"
		output-file-name-pattern="empty-filter.zip"
		max-depth="3"
		base-uri="{$base-uri}">
		<p:with-option name="filter" select="()" />
	</dxar:archive-directory>
	<dxt:check-archives name="empty-filter-check" test-name="empty-filter" description="Empty filter sequence: all files are archived.">
		<p:with-input pipe="result-uri@empty-filter" />
		<p:with-input port="manifest" pipe="manifest@empty-filter" />
		<p:with-option name="expected" select="map{
			'empty-filter.zip' : (
				'root.file-1.xml',
				'root.notes.txt',
				'level-1-1/level-1-1.file-1.xml',
				'level-1-1/level-1-1.file-2.xml',
				'level-1-1/level-2-1/level-2-1.file-1.xml',
				'level-1-1/level-2-1/level-2-1.file-2.xml',
				'level-1-1/level-2-1/level-2-1.notes.txt',
				'level-1-2/level-1-2.data.json',
				'level-1-2/level-1-2.file-1.xml',
				'level-1-2/level-1-2.file-2.xml')
			}" />
	</dxt:check-archives>
	<p:identity name="t04" />
 <p:store href="{$output-directory}/empty-filter/check.xml" serialization="$serialization">
		<p:with-input pipe="check@empty-filter-check" />
	</p:store>

	<!-- 5: root-directory prefix -->
	<dxar:archive-directory name="root-directory"
		input-directory="{$input-directory}"
		output-directory="{$output-directory}/root-directory"
		output-file-name-pattern="root-directory.zip"
		root-directory="prefix"
		max-depth="3"
		base-uri="{$base-uri}">
		<p:with-option name="filter" select="('.*\.xml', '.*\.json')" />
	</dxar:archive-directory>
	<dxt:check-archives name="root-directory-check" test-name="root-directory" description="root-directory 'prefix': entries are placed under prefix/.">
		<p:with-input pipe="result-uri@root-directory" />
		<p:with-input port="manifest" pipe="manifest@root-directory" />
		<p:with-option name="expected" select="map{
			'root-directory.zip' : (
				'prefix/root.file-1.xml',
				'prefix/level-1-1/level-1-1.file-1.xml',
				'prefix/level-1-1/level-1-1.file-2.xml',
				'prefix/level-1-1/level-2-1/level-2-1.file-1.xml',
				'prefix/level-1-1/level-2-1/level-2-1.file-2.xml',
				'prefix/level-1-2/level-1-2.data.json',
				'prefix/level-1-2/level-1-2.file-1.xml',
				'prefix/level-1-2/level-1-2.file-2.xml')
			}" />
	</dxt:check-archives>
	<p:identity name="t05" />
 <p:store href="{$output-directory}/root-directory/check.xml" serialization="$serialization">
		<p:with-input pipe="check@root-directory-check" />
	</p:store>

	<!-- 6: directory-match replaces the placeholder with the directory name -->
	<dxar:archive-directory name="directory-match"
		input-directory="{$input-directory}/level-1-2"
		output-directory="{$output-directory}/directory-match"
		output-file-name-pattern="dir-__ID__.zip"
		directory-match="__ID__"
		base-uri="{$base-uri}">
		<p:with-option name="filter" select="('.*\.xml', '.*\.json')" />
	</dxar:archive-directory>
	<dxt:check-archives name="directory-match-check" test-name="directory-match" description="directory-match: placeholder in the file name pattern is replaced by the directory name.">
		<p:with-input pipe="result-uri@directory-match" />
		<p:with-input port="manifest" pipe="manifest@directory-match" />
		<p:with-option name="expected" select="map{
			'dir-level-1-2.zip' : ('level-1-2.data.json', 'level-1-2.file-1.xml', 'level-1-2.file-2.xml')
			}" />
	</dxt:check-archives>
	<p:identity name="t06" />
 <p:store href="{$output-directory}/directory-match/check.xml" serialization="$serialization">
		<p:with-input pipe="check@directory-match-check" />
	</p:store>

	<!-- 7: one archive per (sub)directory, single filter -->
	<dxar:archive-directories name="directories-single-filter"
		input-directory="{$input-directory}"
		output-directory="{$output-directory}/directories-single-filter"
		output-file-name-pattern="dirs___ID__.zip"
		directory-match="__ID__"
		base-uri="{$base-uri}">
		<p:with-option name="filter" select="'.*\.xml'" />
	</dxar:archive-directories>
	<dxt:check-archives name="directories-single-filter-check" test-name="directories-single-filter" description="archive-directories, single filter: one archive per subdirectory at every depth.">
		<p:with-input pipe="result-uri@directories-single-filter" />
		<p:with-input port="manifest" pipe="manifest@directories-single-filter" />
		<p:with-option name="expected" select="map{
			'dirs_level-1-1.zip' : ('level-1-1.file-1.xml', 'level-1-1.file-2.xml'),
			'dirs_level-2-1.zip' : ('level-2-1.file-1.xml', 'level-2-1.file-2.xml'),
			'dirs_level-1-2.zip' : ('level-1-2.file-1.xml', 'level-1-2.file-2.xml')
			}" />
	</dxt:check-archives>
	<p:identity name="t07" />
 <p:store href="{$output-directory}/directories-single-filter/check.xml" serialization="$serialization">
		<p:with-input pipe="check@directories-single-filter-check" />
	</p:store>

	<!-- 8: one archive per (sub)directory, filters are passed down through the recursion -->
	<dxar:archive-directories name="directories-multiple-filters"
		input-directory="{$input-directory}"
		output-directory="{$output-directory}/directories-multiple-filters"
		output-file-name-pattern="dirs___ID__.zip"
		directory-match="__ID__"
		base-uri="{$base-uri}">
		<p:with-option name="filter" select="('.*\.xml', '.*\.json')" />
	</dxar:archive-directories>
	<dxt:check-archives name="directories-multiple-filters-check" test-name="directories-multiple-filters" description="archive-directories, two filters (XML, JSON) passed down to nested directories; TXT excluded.">
		<p:with-input pipe="result-uri@directories-multiple-filters" />
		<p:with-input port="manifest" pipe="manifest@directories-multiple-filters" />
		<p:with-option name="expected" select="map{
			'dirs_level-1-1.zip' : ('level-1-1.file-1.xml', 'level-1-1.file-2.xml'),
			'dirs_level-2-1.zip' : ('level-2-1.file-1.xml', 'level-2-1.file-2.xml'),
			'dirs_level-1-2.zip' : ('level-1-2.data.json', 'level-1-2.file-1.xml', 'level-1-2.file-2.xml')
			}" />
	</dxt:check-archives>
	<p:identity name="t08" />
 <p:store href="{$output-directory}/directories-multiple-filters/check.xml" serialization="$serialization">
		<p:with-input pipe="check@directories-multiple-filters-check" />
	</p:store>

	<!-- 9: one archive per (sub)directory, empty filter -->
	<dxar:archive-directories name="directories-empty-filter"
		input-directory="{$input-directory}"
		output-directory="{$output-directory}/directories-empty-filter"
		output-file-name-pattern="dirs___ID__.zip"
		directory-match="__ID__"
		base-uri="{$base-uri}">
		<p:with-option name="filter" select="()" />
	</dxar:archive-directories>
 <dxt:check-archives name="directories-empty-filter-check" test-name="directories-empty-filter" description="archive-directories, empty filter sequence: all files of each directory.">
		<p:with-input pipe="result-uri@directories-empty-filter" />
		<p:with-input port="manifest" pipe="manifest@directories-empty-filter" />
		<p:with-option name="expected" select="map{
			'dirs_level-1-1.zip' : ('level-1-1.file-1.xml', 'level-1-1.file-2.xml'),
			'dirs_level-2-1.zip' : ('level-2-1.file-1.xml', 'level-2-1.file-2.xml', 'level-2-1.notes.txt'),
			'dirs_level-1-2.zip' : ('level-1-2.data.json', 'level-1-2.file-1.xml', 'level-1-2.file-2.xml')
			}" />
	</dxt:check-archives>
	<p:identity name="t09" />
 <p:store href="{$output-directory}/directories-empty-filter/check.xml" serialization="$serialization">
  <p:with-input pipe="check@directories-empty-filter-check" />
 </p:store>
 

	<!-- 10: one archive per (sub)directory, root-directory prefix -->
	<dxar:archive-directories name="directories-root-directory"
		input-directory="{$input-directory}"
		output-directory="{$output-directory}/directories-root-directory"
		output-file-name-pattern="dirs___ID__.zip"
		directory-match="__ID__"
		root-directory="prefix/"
		base-uri="{$base-uri}">
		<p:with-option name="filter" select="('.*\.xml', '.*\.txt')" />
	</dxar:archive-directories>
 <dxt:check-archives name="directories-root-directory-check" test-name="directories-root-directory" description="archive-directories, root-directory 'prefix/' (with trailing slash): entries of each archive are placed under prefix/.">
		<p:with-input pipe="result-uri@directories-root-directory" />
		<p:with-input port="manifest" pipe="manifest@directories-root-directory" />
		<p:with-option name="expected" select="map{
			'dirs_level-1-1.zip' : ('prefix/level-1-1.file-1.xml', 'prefix/level-1-1.file-2.xml'),
			'dirs_level-2-1.zip' : ('prefix/level-2-1.file-1.xml', 'prefix/level-2-1.file-2.xml', 'prefix/level-2-1.notes.txt'),
			'dirs_level-1-2.zip' : ('prefix/level-1-2.file-1.xml', 'prefix/level-1-2.file-2.xml')
			}" />
	</dxt:check-archives>
	<p:identity name="t10" />
 <p:store href="{$output-directory}/directories-root-directory/check.xml" serialization="$serialization">
  <p:with-input pipe="check@directories-root-directory-check" />
 </p:store>

	<!-- Report -->
	<p:wrap-sequence wrapper="dxt:test-results">
		<p:with-input pipe="result@t01 result@t02 result@t03 result@t04 result@t05 result@t06 result@t07 result@t08 result@t09 result@t10" />
	</p:wrap-sequence>
	<p:add-attribute attribute-name="failed" attribute-value="{count(//dxt:test[@status = 'failed'])}" />
	<p:add-attribute attribute-name="passed" attribute-value="{count(//dxt:test[@status = 'passed'])}" />
 <p:store href="{resolve-uri($output-directory, $base-uri)}/test-results.xml" serialization="$serialization" name="store-report" />

	<p:variable name="failed" select="xs:integer(/*/@failed)" />
	<p:if test="$fail-on-error and $failed gt 0">
		<p:error code="dxt:test-failed">
			<p:with-input>
				<p:inline><message>{$failed} test(s) failed, see {resolve-uri($output-directory, $base-uri)}/test-results.xml</message></p:inline>
			</p:with-input>
		</p:error>
	</p:if>

</p:declare-step>
