<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
 xmlns:map="http://www.w3.org/2005/xpath-functions/map"
 xmlns:c="http://www.w3.org/ns/xproc-step"
 xmlns:dxt="https://www.daliboris.cz/ns/xproc/test"
 exclude-result-prefixes="xs map c"
 version="3.0">

 <!--
  Input:
   <dxt:check>
    <dxt:archives> c:archive manifests read from the ZIPs (p:archive-manifest),
                   each with @file-name of the ZIP it was read from
    <dxt:generated-manifests> c:archive manifests generated by the library
                   (manifest port), in the same order as the archives
  Output: <dxt:test status="passed|failed">; for every archive it checks
   - @status: archive names and entry names (order-independent) against $expected,
   - @manifest: entry names of the generated manifest against the ZIP content.
 -->

 <xsl:output indent="yes" method="xml" />

 <xsl:param name="test-name" as="xs:string" />
 <xsl:param name="description" as="xs:string" select="''" />
 <xsl:param name="expected" as="map(xs:string, xs:string*)" />

 <xsl:template match="/dxt:check">
  <xsl:variable name="archives" select="dxt:archives/c:archive" />
  <xsl:variable name="generated" select="dxt:generated-manifests/c:archive" />
  <xsl:variable name="file-names" select="sort(distinct-values(($archives/@file-name, map:keys($expected))))" />
  <xsl:variable name="results" as="element()*">
   <xsl:if test="count($generated) ne count($archives)">
    <dxt:manifest-count status="failed" archives="{count($archives)}" manifests="{count($generated)}" />
   </xsl:if>
   <xsl:for-each select="$file-names">
    <xsl:variable name="file-name" select="." />
    <xsl:variable name="archive" select="$archives[@file-name = $file-name]" />
    <xsl:variable name="generated-manifest" select="$generated[index-of($archives/@file-name, $file-name)[1]]" />
    <xsl:variable name="expected-entries" select="sort($expected($file-name))" />
    <xsl:variable name="actual-entries" select="sort($archive/c:entry/@name ! string())" />
    <xsl:variable name="manifest-entries" select="sort($generated-manifest/c:entry/@name ! string())" />
    <xsl:variable name="status" select="
     if (empty($archive)) then 'missing'
     else if (not(map:contains($expected, $file-name))) then 'unexpected'
     else if (deep-equal($expected-entries, $actual-entries)) then 'passed'
     else 'failed'" />
    <xsl:variable name="manifest-status" select="
     if (empty($archive)) then 'not-checked'
     else if (empty($generated-manifest)) then 'missing'
     else if (deep-equal($manifest-entries, $actual-entries)) then 'passed'
     else 'failed'" />
    <dxt:archive file-name="{$file-name}" status="{$status}" manifest="{$manifest-status}">
     <xsl:if test="$status = ('failed', 'unexpected')">
      <xsl:for-each select="$actual-entries[not(. = $expected-entries)]">
       <dxt:unexpected-entry name="{.}" />
      </xsl:for-each>
     </xsl:if>
     <xsl:if test="$status = 'failed'">
      <xsl:for-each select="$expected-entries[not(. = $actual-entries)]">
       <dxt:missing-entry name="{.}" />
      </xsl:for-each>
     </xsl:if>
     <xsl:if test="$manifest-status = 'failed'">
      <xsl:for-each select="$manifest-entries[not(. = $actual-entries)]">
       <dxt:manifest-only-entry name="{.}" />
      </xsl:for-each>
      <xsl:for-each select="$actual-entries[not(. = $manifest-entries)]">
       <dxt:archive-only-entry name="{.}" />
      </xsl:for-each>
     </xsl:if>
    </dxt:archive>
   </xsl:for-each>
  </xsl:variable>
  <xsl:variable name="passed" select="every $r in $results satisfies ($r/@status = 'passed' and $r/@manifest = ('passed', 'not-checked'))" />
  <dxt:test name="{$test-name}" status="{if ($passed) then 'passed' else 'failed'}">
   <xsl:if test="$description != ''">
    <xsl:attribute name="description" select="$description" />
   </xsl:if>
   <xsl:sequence select="$results" />
  </dxt:test>
 </xsl:template>

</xsl:stylesheet>
